apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: db
   namespace: online-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: venkatanagababuallu/pythonlibrary:dbimage
          ports:
            - containerPort: 3306


